# Generated by Django 4.1.2 on 2022-10-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_article_articles_alter_articles_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Reviews',
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
